### Bridging Victoria: Stories from the archaeological past

This timeline is the result of a colloborative effort from University of Victoria anthropology students and the Royal British Columbia Museum.
